### ISSUE TITLE
Add docs for MSI support

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#1036]
MSI installs for Elastic Agent are added via https://github.com/elastic/elastic-stack-installers/pull/212. This will GA in 8.14.

The [Install Elastic Agent](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html) section of the docs will need updates, and possible the [install command parameters](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-install-command).

**Comment by amitkanfer** [comment]
For MSI, here's my suggestion:

MSI is the file format and command line utility for the [Windows Installer](https://en.wikipedia.org/wiki/Windows_Installer). Windows Installer (previously known as Microsoft Installer) is an interface for Microsoft Windows that’s used to install and manage software on Windows systems. This section covers installing Elastic Agent through the MSI package repository.

### Requirements:
- Download the latest Elastic Agent MSI binary from the [download](https://www.elastic.co/downloads/elastic-agent) page.
- The MSI must run **as an administrator** (the installer will not start w/o admin permissions)

### Running from command line:
In order to fully install **and enroll** Agent with Fleet, command line parameters are needed via the `INSTALLARGS` option. An example for 8.13.2 Agent:
```
elastic-agent-8.13.2-windows-x86_64.msi INSTALLARGS="--url=<URL> --enrollment-token=<TOKEN>"
```

For troubleshooting, `msiexec` can be used to create installation logs:
```
msiexec -i elastic-agent-8.13.2-windows-x86_64.msi INSTALLARGS="--url=<URL> --enrollment-token=<TOKEN>" -L*V "log.txt"
```

### Installation notes:
* If `INSTALLARGS` are not provided, the MSI will copy the files to a temp folder and finish.
* If `INSTALLARGS` are provided, the MSI will copy the files to a temp folder and then run the `elastic-agent install` command with the provided args. If the install flow is successful, the temp folder is deleted.
* If `INSTALLARGS` are provided but the `elastic-agent install` command fails - the top folder is NOT deleted to allow further troubleshooting.
* if the `elastic-agent install` command fails (for any reason), the MSI will rollback all changes.


### Upgrades:
Upgrades are not supported and prevented by the MSI itself. Agent upgrades shall happen via fleet.


### Custom location:
Starting version 8.13 It's also possible to override the installation folder by executing the MSI from command line as such:
`msiexec /i "<full path to msi file>" INSTALLDIR="<path of custom folder>"`

**Comment by amitkanfer** [comment]
@cmacknz @strawgate if i can have your eyes on [this](https://github.com/elastic/ingest-docs/issues/1036#issuecomment-2064224101) one please.

**Comment by strawgate** [comment]
Should we note that install will fail if enrollment fails and if you do not want this behavior you should add --delay-enroll ?

**Comment by amitkanfer** [comment]
> Should we note that install will fail if enrollment fails and if you do not want this behavior you should add --delay-enroll ?

Yes, we probably should
