### ISSUE TITLE
Document minimum permissions required to run Oracle Metricbeat module or Oracle Integration

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/ingest-docs#226]
The pages:
- https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-oracle.html
- https://docs.elastic.co/integrations/oracle

Do not document the permissions to grant the user in order to make the module/integration work.
We mention `SYSDBA` but it might be too broad.

**Comment by 111andre111** [comment]
If I understand correctly it's enough to grant the `SELECT` privilege to the given user:
https://www.oracletutorial.com/oracle-administration/oracle-grant-select/

**Comment by agithomas** [comment]
Read permission on below mentioned tables / views are also important for the Oracle Integration to work correctly
```
V$SYSMETRIC;
V$PGASTAT;
v$sgastat;
gv$session;
v$process;
V$LIBRARYCACHE;
sys.dba_data_files
sys.dba_temp_files
dba_free_space
dba_temp_free_space
dba_jobs
V$SYSTEM_WAIT_CLASS
```

**Comment by devamanv** [comment]
Across all the data streams in the Oracle integration, we make use of the following datasources:

1. ### Dynamic Performance Views (V$ Views):
 ```
V$BUFFER_POOL_STATISTICS
v$sesstat
v$statname
v$session
v$sysstat
V$LIBRARYCACHE
V$SYSTEM_WAIT_CLASS
V$PGASTAT
v$sgastat
```

These views are typically accessible to users with basic database querying privileges. However, some of these views, especially those related to performance statistics and system-level information, may require additional privileges to view certain statistics. Users may need elevated privileges such as `SELECT_CATALOG_ROLE` or `SELECT ANY DICTIONARY`. The latter being more permissive, which is **NOT RECOMMENDED** to ensure the security and integrity of the database. 

See Also:
- [Oracle Official docs](https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/dynamic-performance-views.html#GUID-8C5690B0-DE10-4460-86DF-80111869CF4C) for more information about each of the views and their respective schemas


2. ### Global Views(GV$):
```
gv$session
```

 GV$ views are cluster-aware views, meaning they provide information about the entire Oracle RAC cluster rather than just a single instance. When you query a GV$ view, you can see data aggregated from all instances within the RAC cluster unlike V$ views which are instance-specific views. 

 ***Permissions required: You must grant the `SELECT` privilege on the `gv$session` view to query the information provided by the view. *** 


3. ### System Tables:

```
sys.dba_data_files
sys.dba_temp_files
dba_free_space
dba_temp_free_space
dba_jobs
```

Access to system tables usually requires elevated privileges like `SYSDBA`, as these tables contain information about database files, free space, and administrative jobs. Some views may require specific system privileges beyond the basic `SELECT` privilege. For example, to query tables in the `SYS` schema, you typically need the `SELECT ANY TABLE` privilege. 
Access to these tables should be restricted and limited to users or roles with specific administrative responsibilities. There's a `SYSTEM` administrative account as well, which unlike `SYS`, does not have unrestricted access to all data dictionary tables and views[^1]. It has only the privileges necessary for basic database administration.

### Bottomline: 
- V$ Views are fixed views because they cannot be altered or removed by a database administrator, granting the necessary `SELECT` privileges to the user or role executing queries in your Oracle database should be enough. This is what is also suggested by @111andre111. 
- `SYS` owns the dynamic performance tables, whose names begin with `V_$`. Views are created on these tables, and then public synonyms prefixed with `V$`. Principle of least privilege applies here too, in that only `SELECT` should be granted. For more advanced queries, the official docs[^2] suggest something like 

    > You can query the dynamic performance views to extract information from them. However, only simple queries are supported. If sorts, joins, `GROUP BY` clauses and the like are needed, then you should copy the information from each `V$` view into a table (for example, using a `CREATE TABLE ... AS SELECT` statement), and then query from those tables. 

- The `SELECT_CATALOG_ROLE` includes the necessary privileges to query the dynamic performance views. Specifically, it grants the `SELECT` privilege on various data dictionary views, including those related to dynamic performance information. 

[^1]: https://docs.oracle.com/cd/E11882_01/server.112/e10897/users_secure.htm#CHDBJCHH
[^2]: (https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/about-dynamic-performance-views.html#GUID-2B9DD73A-4C3A-467A-A934-01B705AB77A8)

@agithomas @lucabelluccini I have tried to put together this information as part of documenting the permissions needed. Please take a look, and suggest changes if you it lacks details, and where should these documentation changes go.

**Comment by lucabelluccini** [comment]
Thank you @devamanv 

If those settings are validated to work with the Oracle Metricbeat and Oracle Integration for Elastic Agent, I would ensure to involve the ingest/observability doc team and port those in a paragraph of both the old metricbeat and the new oracle integration.

- https://docs.elastic.co/integrations/oracle
- https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-oracle.html

**Comment by lalit-satapathy** [comment]
@devamanv,

What is pending on this?

CC: @alaudazzi @agithomas

**Comment by agithomas** [comment]
@devamanv , we are seeing multiple SDHs reported as the customer lacks knowledge about the permissions needed. Will you be able to take this task immediately. Should i need to take it up, please let me know. 

cc @lalit-satapathy

**Comment by alaudazzi** [comment]
@devamanv 

As suggested [here](https://github.com/elastic/ingest-docs/issues/226#issuecomment-1713685427), the following pages 
    - https://docs.elastic.co/integrations/oracle
    - https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-oracle.html
need to be updated with more specific settings.
I can support you from the doc side, if you can clarify what these settings are. Happy to sync over zoom.

**Comment by alaudazzi** [comment]
@agithomas 
I've reached out to @devamanv to get more clarity on the required settings before I start any content rework. It looks like you are the one I should talk to :-) 
See Aman comment below:

> Hi Arianna. Thanks for reaching out. Happy to help you get started. Would you also mind talking to 
> [@Agi](https://elastic.slack.com/team/U0377DYRMPV)
>  about this? Although, I just shared my findings about the minimum permissions, he is probably the best person to confirm where these permissions/settings need to be applied exactly.

**Comment by lucabelluccini** [comment]
Thank you @alaudazzi & @agithomas - this should make it easy for users to know what are the permissions necessary to use the integration ❤️
