### ISSUE TITLE
[Fleet]: Release notes version selection dropdown is not working.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#229]
**Description:** 
Unable to select different kibana versions under Release notes.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/release-notes-8.8.0.html

**Screen Recording:**

https://github.com/elastic/ingest-docs/assets/77374876/c3ca6a0f-453a-42cd-b2a4-83f5a8d69b9d

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amitkanfer** [comment]
@karenzone who can help us with this?

**Comment by karenzone** [comment]
@kilfoyle, can you take a look, please?

**Comment by kilfoyle** [comment]
Thanks for reporting this @amolnater-qasource!

In this case I think the behaviour is as designed. The warning (similar to what we have in other docs sets) is alerting people that the 8.7.1 Release Notes page is not available in the version 8.6 or version 8.8 documentation.

For the docs at a given release level (e.g. 8.6) we intentionally include only release notes pages for the related minor releases (e.g. for 8.6.0, 8.6.1 and 8.6.2). This is reflected in the navigation and on each release notes landing page:
![Screenshot 2023-06-14 at 4 52 26 PM](https://github.com/elastic/ingest-docs/assets/41695641/34622be9-27b5-4e43-8380-87b84793281e)

The design is intentional because:
 - It can be confusing to people to read about, for example, `8.8.1` features in our `8.7` docs.
 - Including release notes across many versions of the documentation has a prohibitively high maintenance cost, since even very small changes need to be back-fitted across many releases.

I hope the explanation helps. Please let me know what you think.

**Comment by amolnater-qasource** [comment]
Hi @kilfoyle 

Thank you for the detailed explanation, now we understand the required working for this page.

However, for a user it might be little confusing, as the dropdown is available there like any other page to select the versions.
For that reason we have raised this issue.

As this is intentional, hence we are closing this issue.

Thanks

**Comment by kilfoyle** [comment]
Thanks very much @amolnater-qasource!
