### ISSUE TITLE
[Fleet]: Experimental badge is available and API reference tab is missing under Integrations screenshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#663]
**Description:**
Experimental badge is available and API reference tab is missing under Integrations screenshot.
- Visualizations is renamed to Saved search too.

**Link(s):**
https://www.elastic.co/guide/en/observability/8.11/logs-metrics-get-started.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/215d07e0-fc8c-4da2-b7c3-ba4baba610f4)

**Expected Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/4fb694dd-78dd-4b2b-8ca9-a9d5a68df513)
![image](https://github.com/elastic/ingest-docs/assets/77374876/7b77e1a9-13f1-44ee-b5cd-b55c382c5cc5)

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @kilfoyle

**Comment by kilfoyle** [comment]
@amolnater-qasource  I don't see that "Elastic Agent" screenshot on the [Get started with logs and metrics](https://www.elastic.co/guide/en/observability/8.11/logs-metrics-get-started.html) page. It might have been removed since you opened this issue. I looked through other tutorials in the same book and couldn't find that graphic with the "experimental" tag. So, perhaps it's safe to close this issue?

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated the docs for 8.14.0 release and found that they are **updated now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/e5e22d8c-79ca-487e-abd6-b9c0fe8e3f2d)

Hence, we are marking this as **QA:Validated**.

Thanks!
