### ISSUE TITLE
Agent tamper protection feature docs are not available.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#676]
**Description:**
Documentation needs to be updated for Agent tamper protection feature released in 8.11.0.
- Not available under Agent policy and Uninstall agent documentations.

![image](https://github.com/elastic/ingest-docs/assets/77374876/e40ccf65-d246-4f81-ad0a-e415030f5f4f)

**Link(s):**
https://www.elastic.co/guide/en/fleet/current/uninstall-elastic-agent.html
https://www.elastic.co/guide/en/fleet/current/agent-policy.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/46f7892e-c028-42aa-94ee-5006efdfb912)

![image](https://github.com/elastic/ingest-docs/assets/77374876/3b76c31c-511e-464e-be69-5138ba12c1a8)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
JFI @kilfoyle 
We have raised this issue, just to keep track of the missing docs for this feature and complete the testing for the same when available.

Thanks!

**Comment by kilfoyle** [comment]
I think this is resolved now, by https://github.com/elastic/ingest-docs/pull/674

The "[Uninstall Elastic Agents from edge hosts](https://www.elastic.co/guide/en/fleet/current/uninstall-elastic-agent.html)" page has a note about tamper protection settings:

![Screenshot 2023-11-14 at 4 17 19 PM](https://github.com/elastic/ingest-docs/assets/41695641/72cda088-14ed-4c51-a350-1f0547b8937b)

For the [Elastic Agent policies page](https://www.elastic.co/guide/en/fleet/current/agent-policy.html), I asked if we should add a note about tamper protection. However, since the setting is only available as part of Elastic Defend, we think it shouldn't be mentioned here (but it is mentioned in the Security docs, of course). Discussion about that is [here](https://github.com/elastic/ingest-docs/pull/674#issuecomment-1810386099).

**Comment by amolnater-qasource** [comment]
Hi @kilfoyle 

Thank you for the update.
We have validated the updated docs at links:

- https://www.elastic.co/guide/en/fleet/current/uninstall-elastic-agent.html
- https://www.elastic.co/guide/en/security/8.11/agent-tamper-protection.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/8e00f4d9-b413-47e4-bc66-648063f8992a)

Hence, we are closing this issue and marking as **QA:Validated**.

Thanks!!
