### ISSUE TITLE
Update the ES output presets doc

### ISSUE THREAD

**Issue by jlind23** [elastic/ingest-docs#869]
When we introduced the ES output presets in Kibana we made some mistakes on the settings name.
The related issue is: https://github.com/elastic/kibana/issues/175892

We should update the docs to reflect these changes.
In the meantime we need to improve the docs on a couple of other items:

- [x] We need to explicitly state that presets values prevail over any other settings.
- [x] If users want to change one setting of a preset they will have to fallback on the custom mode and manually add all values to the custom yaml box.
One workflow offered by @kpollich is :
- Goal: use Balanced preset with one minor value changed
    - Go to docs -> Copy balanced preset YML -> Paste into UI -> Automatically assigns Custom preset -> Change the given value
    - Context: we want presets to be "good enough" - don't want to promote overriding them. Presets are not "templates".

- [x] This blog post need to be updated - https://www.elastic.co/blog/using-elastic-agent-performance-presets-in-8-12 
- [x] This tab needs to be updated - https://www.elastic.co/guide/en/fleet/current/es-output-settings.html
    

These changes should be backported to 8.12 branch and will land in one of the 8.12 patch release.

**Comment by kilfoyle** [comment]
Thanks for opening this @jlind23!

This [PR](https://github.com/elastic/ingest-docs/pull/870) includes the term fixes and the workaround steps.

I wasn't involved with that blog though. @nimarezainia can you please help with that part?

**Comment by nimarezainia** [comment]
@jlind23 I can change the blog. What exactly is the concern? in the blog we do say what the default values are and the fields that were changed. The naming of those fields are not configurations rather just that, a name. Is that what you are asking to change? for example change "compression" to "compression_level"? 

regarding the custom presets, I read the blog again. I feel like it's fine as far as the description goes. Of course points back t the public docs for more detail so that needs to be crisp and clear.

Let me know where you think the blog needs to be changed. thanks.

**Comment by jlind23** [comment]
Spoke with @nimarezainia this morning about this and gave him the pointers to the right settings names.

**Comment by kilfoyle** [comment]
The docs are fixed up now, via https://github.com/elastic/ingest-docs/pull/870

**Comment by jlind23** [comment]
@kilfoyle Can I close this issue as done then?

**Comment by kilfoyle** [comment]
@jlind23  Yes. The only remaining piece is the blog, which I see Nima is looking after. So it's good to close. Thanks!

**Comment by nimarezainia** [comment]
blog is updated now. thanks folks.
